import { Metadata, ResolvingMetadata } from 'next';
import { Sidebar } from "@/components/sidebar";
import { Topbar } from "@/components/topbar";
import { MarketTicker } from "@/components/market-ticker";
import { cn } from "@/lib/utils";

interface PageProps {
    params: { asset: string };
}

// SEO Strategy: Dynamic Metadata Generation
// This ensures that when someone searches for "[Asset] technical analysis", our page shows relevant info.
export async function generateMetadata(
    { params }: PageProps,
    parent: ResolvingMetadata
): Promise<Metadata> {
    const asset = params.asset.toUpperCase();

    return {
        title: `${asset} Real-time AI Technical Analysis | ChartHelpAI`,
        description: `Get instant AI-powered technical analysis for ${asset}. Discover key support/resistance levels, patterns, and sentiment analysis powered by Gemini 1.5 Pro.`,
        openGraph: {
            title: `${asset} Technical Analysis Dashboard`,
            description: `Live neural network scanner for ${asset} chart patterns and price action.`,
            images: [`/api/og/analysis?asset=${asset}`], // Dynamic OG images drive social CTR
        },
        alternates: {
            canonical: `/analysis/${params.asset.toLowerCase()}`, // Prevents duplicate content issues
        }
    };
}

export default function AnalysisPage({ params }: PageProps) {
    const asset = params.asset.toUpperCase();

    // SEO Strategy: JSON-LD (Schema.org)
    // Helps Google understand the page content type (AI Tool + Financial Product)
    const jsonLd = {
        "@context": "https://schema.org",
        "@type": ["SoftwareApplication", "FinancialProduct"],
        "name": `ChartHelpAI ${asset} Scanner`,
        "description": `Advanced AI technical analysis tool for ${asset} trading pairs.`,
        "applicationCategory": "FinanceApplication",
        "operatingSystem": "Web",
        "offers": {
            "@type": "Offer",
            "price": "0.00",
            "priceCurrency": "USD"
        },
        "featureList": "Pattern Recognition, Sentiment Analysis, Level Detection",
    };

    return (
        <div className="flex h-screen overflow-hidden bg-background text-foreground">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />

            <Sidebar onUpgrade={() => { }} />

            <main className="flex-1 flex flex-col overflow-hidden relative">
                <MarketTicker />
                <Topbar />

                <div className="flex-1 overflow-y-auto p-4 lg:p-8">
                    <div className="max-w-4xl mx-auto space-y-8">
                        <div>
                            <h1 className="text-3xl lg:text-5xl font-black italic tracking-tighter uppercase mb-4">
                                {asset} <span className="text-brand-primary">Neural Analysis</span>
                            </h1>
                            <p className="text-sm lg:text-base text-foreground/60 leading-relaxed font-medium">
                                Technical breakdown for <span className="text-foreground font-bold">{asset}</span> generated by our proprietary trading intelligence engine.
                                This analysis identifies structural shifts, harmonic patterns, and volume exhaustion points.
                            </p>
                        </div>

                        {/* Placeholder for actual analysis content or a prompt to start scan */}
                        <div className="glass-morphism h-96 border-dashed border-2 border-border/50 flex flex-col items-center justify-center text-center p-8">
                            <div className="w-16 h-16 bg-brand-primary/10 rounded-2xl flex items-center justify-center mb-6 text-brand-primary animate-pulse">
                                <span className="font-black italic text-2xl">AI</span>
                            </div>
                            <h2 className="text-xl font-black italic tracking-tight uppercase mb-2">Awaiting Live Feed</h2>
                            <p className="text-sm text-foreground/40 font-medium max-w-sm">
                                To get the latest analysis for {asset}, upload a recent chart screenshot in the dashboard.
                            </p>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}
